<a href="https://colab.research.google.com/github/LadySoto/Curso_pandas_manipulacion_transformacion_datos/blob/main/Desafio1_ventas_online.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Desaf√≠o Ventas Online**

In [2]:
import pandas as pd

##**1. Lectura de datos:**

In [3]:
ruta_datos = '/content/drive/MyDrive/Colab Notebooks/Ruta: Aprendiendo a hacer ETL (7)/Curso 4-7 Data Science: Pandas: manupulacion y transformacion de datos/Desafio 1: Ventas Online/dados_vendas_clientes.json'
datos = pd.read_json(ruta_datos)
datos.head()

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [4]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   dados_vendas  5 non-null      object
dtypes: object(1)
memory usage: 172.0+ bytes

In [5]:
datos = pd.json_normalize(datos['dados_vendas'])

In [6]:
datos.head()

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JO√£O Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

##**2. Eliminar datos en listas dentro del DataFrame:**

In [7]:
columnas = list(datos.columns)
columnas

['Data de venda', 'Cliente', 'Valor da compra']

In [8]:
datos = datos.explode(columnas[1:])

In [9]:
datos.reset_index(inplace=True, drop=True)

In [10]:
datos.head()

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
1    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4    07/06/2022  Isabely JOanes 738       R$ 825,31

##**3. Verificar tipos de datos:**

In [11]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

##**4. Identificar columnas num√©ricas:**

In [12]:
datos

#La columna 'valor da compra' debe de ser num√©rica

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321        R$ 836,5
1     06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2     06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3     06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4     07/06/2022  Isabely JOanes 738       R$ 825,31
5     07/06/2022  Isabely JOanes 738       R$ 168,07
6     07/06/2022  Isabely JOanes 738       R$ 339,18
7     07/06/2022  Isabely JOanes 738       R$ 314,69
8     08/06/2022  Isabely JOanes 738       R$ 682,05
9     08/06/2022    JO√£O Gabriel 671       R$ 386,34
10    08/06/2022  Julya meireles 914       R$ 622,65
11    08/06/2022  Julya meireles 914       R$ 630,79
12    09/06/2022  Julya meireles 914        R$ 390,3
13    09/06/2022     MaRIA Julia 444       R$ 759,16
14    09/06/2022     MaRIA Julia 444       R$ 334,47
15    09/06/2022     MaRIA Julia 444       R$ 678,78
16    10/06/2022     MaRIA Julia 444       R$ 314,24
17    10/06/2022     PEDRO PASCO 812       R$ 311,15
18    10/06/2022    Paulo castro 481       R$ 899,16
19    10/06/2022   Thiago fritzz 883       R$ 885,24

In [13]:
datos['Valor da compra'] = datos['Valor da compra'].apply(lambda x: x.replace('R$','').replace(',','').strip())

In [14]:
import numpy as np

In [15]:
datos['Valor da compra'] = datos['Valor da compra'].astype(np.float64)

##**5. Manipulaci√≥n de un texto:**

**1. Pasar todo a min√∫scula:**

In [18]:
datos['Cliente'] = datos['Cliente'].str.lower()
datos['Cliente'].head()

0       @ana _lucia 321
1    diego armandiu 210
2    diego armandiu 210
3    diego armandiu 210
4    isabely joanes 738
Name: Cliente, dtype: object

**2. Eliminar caracteres especiales:**

In [21]:
datos['Cliente'] = datos['Cliente'].str.replace('[^a-z]',' ', regex=True)
datos['Cliente'].head()

0        ana  lucia
1    diego armandiu
2    diego armandiu
3    diego armandiu
4    isabely joanes
Name: Cliente, dtype: object

##**6. Datos de tiempo:**

In [26]:
# Transformar para el tipo datetime definiendo el formato de fecha como DD/MM/AAAA ('%d/%m/%Y')
datos['Data de venda'] = pd.to_datetime(datos['Data de venda'], format='%d/%m/%Y')

In [23]:
datos

   Data de venda             Cliente  Valor da compra
0     2022-06-06      ana  lucia               8365.0
1     2022-06-06  diego armandiu              57333.0
2     2022-06-06  diego armandiu               3928.0
3     2022-06-06  diego armandiu              51234.0
4     2022-06-07  isabely joanes              82531.0
5     2022-06-07  isabely joanes              16807.0
6     2022-06-07  isabely joanes              33918.0
7     2022-06-07  isabely joanes              31469.0
8     2022-06-08  isabely joanes              68205.0
9     2022-06-08    jo o gabriel              38634.0
10    2022-06-08  julya meireles              62265.0
11    2022-06-08  julya meireles              63079.0
12    2022-06-09  julya meireles               3903.0
13    2022-06-09     maria julia              75916.0
14    2022-06-09     maria julia              33447.0
15    2022-06-09     maria julia              67878.0
16    2022-06-10     maria julia              31424.0
17    2022-06-10     pedro pasco              31115.0
18    2022-06-10    paulo castro              89916.0
19    2022-06-10   thiago fritzz              88524.0

In [24]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     datetime64[ns]
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 612.0+ bytes

In [25]:
# Calcular el total recaudado en compras por cada cliente
total_compras = datos.groupby(['Cliente'])['Valor da compra'].sum()

total_compras

Cliente
 ana  lucia             8365.0
diego armandiu        112495.0
isabely joanes        232930.0
jo o gabriel           38634.0
julya meireles        129247.0
maria julia           208665.0
paulo castro           89916.0
pedro pasco            31115.0
thiago fritzz          88524.0
Name: Valor da compra, dtype: float64